apiVersion: v1
kind: Service
metadata:
  name: theband-service
spec:
  type: NodePort
  selector:
    app: theband 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31110
